# How to use :
# docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '2'
services:

  nexus:
    # https://hub.docker.com/r/sonatype/nexus
    hostname: NEXUS
    container_name: docker_nexus
    image: sonatype/nexus:2.14.15
    environment: 
      MAX_HEAP: 768m
      MIN_HEAP: 256m
    volumes:
      - ./nexus/data:/sonatype-work
      - ./nexus/plugin:/opt/sonatype/nexus/nexus/WEB-INF/plugin-repository
    ports:
      - 8081:8081
    networks: 
      vpn:
        ipv4_address: 172.168.40.2
    restart: unless-stopped


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.40.0/24
          gateway: 172.168.40.1

