# How to use :
# docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '2'
services:
  attacker:
    hostname: attacker
    container_name: docker_attacker
    build:
      context: ./attacker
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["sh"]
    networks: 
      vpn:
        ipv4_address: 172.168.50.2
    restart: on-failure

  nexus_oss_21409:
    hostname: NEXUS_OSS_21409
    container_name: docker_nexus_oss_21409
    image: sonatype/nexus:2.14.9-01
    environment: 
      MAX_HEAP: 768m
      MIN_HEAP: 256m
    volumes:
      - ./nexus/2_14_09:/sonatype-work
    ports:
      - 8009:8081
      - 2209:4444
    networks: 
      vpn:
        ipv4_address: 172.168.50.9
    restart: unless-stopped

  nexus_oss_21414:
    hostname: NEXUS_OSS_21414
    container_name: docker_nexus_oss_21414
    image: sonatype/nexus:2.14.14-01
    environment: 
      MAX_HEAP: 768m
      MIN_HEAP: 256m
    volumes:
      - ./nexus/2_14_14:/sonatype-work
    ports:
      - 8014:8081
      - 2214:4444
    networks: 
      vpn:
        ipv4_address: 172.168.50.14
    restart: unless-stopped

  nexus_oss_21415:
    hostname: NEXUS_OSS_21415
    container_name: docker_nexus_oss_21415
    image: sonatype/nexus:2.14.15-01
    environment: 
      MAX_HEAP: 768m
      MIN_HEAP: 256m
    volumes:
      - ./nexus/2_14_15:/sonatype-work
    ports:
      - 8015:8081
      - 2215:4444
    networks: 
      vpn:
        ipv4_address: 172.168.50.15
    restart: unless-stopped


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.50.0/24
          gateway: 172.168.50.1

